/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StaticFieldAccess */

#ifndef _Included_StaticFieldAccess
#define _Included_StaticFieldAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StaticFieldAccess
 * Method:    accessField
 * Signature: ()V
 */
JNIEXPORT void JNICALL _Java_StaticFieldAccess_accessField(JNIEnv *env, jobject obj) {
    jfieldID fid;
    jclass cls = env->GetObjectClass(obj);
    fid = env->GetStaticFieldID(cls, "si", "I");
    jint si = env->GetStaticIntField(cls, fid);
    printf("Origin value: %d\n", si);
    env->SetStaticIntField(cls, fid, -1);
}

#ifdef __cplusplus
}
#endif
#endif
